### ISSUE TITLE
ModuleNotFoundError: No module named 'torchsde'

### ISSUE THREAD

**Issue by zacjiang** [sihyun-yu/digan#5]
Hi,

Thank you for your work. When I run generate_videos.py on the pretrained checkpoints, it gave out the following error:

Loading networks from "../digan/pretrained/ucf-101-train-test.pkl"...
Traceback (most recent call last):
  File "src/scripts/generate_videos.py", line 59, in <module>
    generate_videos()
  File "/mnt/home/v_jiangshihao/miniconda3/envs/digan/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/home/v_jiangshihao/miniconda3/envs/digan/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/mnt/home/v_jiangshihao/miniconda3/envs/digan/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/home/v_jiangshihao/miniconda3/envs/digan/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/mnt/home/v_jiangshihao/miniconda3/envs/digan/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "src/scripts/generate_videos.py", line 38, in generate_videos
    G = legacy.load_network_pkl(f)['G_ema'].to(device).eval() # type: ignore
  File "/mnt/home/v_jiangshihao/digan_new/src/legacy.py", line 21, in load_network_pkl
    data = _LegacyUnpickler(f).load()
  File "/mnt/home/v_jiangshihao/digan_new/src/torch_utils/persistence.py", line 190, in _reconstruct_persistent_obj
    module = _src_to_module(meta.module_src)
  File "/mnt/home/v_jiangshihao/digan_new/src/torch_utils/persistence.py", line 226, in _src_to_module
    exec(src, module.__dict__) # pylint: disable=exec-used
  File "<string>", line 14, in <module>
ModuleNotFoundError: No module named 'torchsde'

Do you know what's the cause of that? Thanks for your help!

**Comment by zacjiang** [comment]
I solved it by installing torchsde. Not sure why it comes up as an error.
